-- MediaPlayer Spatial Tool localization compatibility loader
-- Loads translated phrases clientside so the tool UI also works when only Lua files are distributed.

local Translations = {
	["en"] = {
		["tool.mediaplayer_spatial.name"] = "Spatial Media Player",
		["tool.mediaplayer_spatial.desc"] = "Pin MediaPlayer audio to the world or make it follow an entity.",
		["tool.mediaplayer_spatial.0"] = "Left click: create or reopen a spatial source. Right click: remove it. Reload: reopen the request UI.",
		["tool.mediaplayer_spatial.help_target"] = "Left click a prop, player, or NPC to make the audio follow it, or left click the world to pin the sound in place.",
		["tool.mediaplayer_spatial.help_popup"] = "The popup uses the normal MediaPlayer request browser. Set loop forever or choose how many extra loops to queue.",
		["tool.mediaplayer_spatial.help_remove"] = "Right click removes the matching spatial source. Reload reopens the request popup for an existing source.",
		["tool.mediaplayer_spatial.section.client"] = "Client settings",
		["tool.mediaplayer_spatial.section.client_desc"] = "These settings only affect your local game client.",
		["tool.mediaplayer_spatial.section.advanced"] = "Advanced settings",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "For debugging and legacy behavior.",
		["tool.mediaplayer_spatial.section.shared"] = "Shared and server settings",
		["tool.mediaplayer_spatial.section.shared_desc"] = "These settings may require admin privileges on multiplayer servers.",
		["tool.mediaplayer_spatial.cvar.debug"] = "Debug logging",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "Allow webpage requests",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "Queue limit",
		["tool.mediaplayer_spatial.cvar.resolution"] = "Browser resolution",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "Enable 3D audio",
		["tool.mediaplayer_spatial.cvar.volume"] = "Volume",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "Mute when Garry's Mod is unfocused",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "Draw thumbnails",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "Proximity minimum",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "Proximity maximum",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "Spatial hear radius",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "Maximum extra loop count",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "Fullscreen (deprecated; unused)",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "JS console filter",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = all HTML console messages, 1 = none.",
		["mediaplayer.spatial.loop_forever"] = "Loop forever",
		["mediaplayer.spatial.extra_loops"] = "Extra loops",
		["mediaplayer.spatial.footer_hint"] = "The link uses the normal MediaPlayer request page. Finite loops are counted after the first play.",
		["mediaplayer.spatial.error_anchor_missing"] = "The selected spatial media anchor no longer exists.",
		["mediaplayer.spatial.error_empty_url"] = "Please enter a media URL first.",
		["mediaplayer.spatial.error_invalid_url"] = "The requested URL was invalid.",
		["mediaplayer.spatial.error_request_failed"] = "Request failed: %s",
		["mediaplayer.spatial.error_anchor_network"] = "Could not open the spatial media request window because the anchor did not finish networking in time.",
	},
	["es-ES"] = {
		["tool.mediaplayer_spatial.name"] = "Reproductor multimedia espacial",
		["tool.mediaplayer_spatial.desc"] = "Fija el audio de MediaPlayer en el mundo o haz que siga a una entidad.",
		["tool.mediaplayer_spatial.0"] = "Clic izquierdo: crear o reabrir una fuente espacial. Clic derecho: eliminarla. Recargar: reabrir la interfaz de solicitud.",
		["tool.mediaplayer_spatial.help_target"] = "Haz clic izquierdo en un prop, jugador o NPC para que el audio lo siga, o clic izquierdo en el mundo para fijar el sonido en su sitio.",
		["tool.mediaplayer_spatial.help_popup"] = "La ventana usa el navegador de solicitud normal de MediaPlayer. Activa el bucle infinito o elige cuántas repeticiones extra poner en cola.",
		["tool.mediaplayer_spatial.help_remove"] = "El clic derecho elimina la fuente espacial correspondiente. Recargar vuelve a abrir la ventana de solicitud para una fuente existente.",
		["tool.mediaplayer_spatial.section.client"] = "Ajustes del cliente",
		["tool.mediaplayer_spatial.section.client_desc"] = "Estos ajustes solo afectan a tu cliente local.",
		["tool.mediaplayer_spatial.section.advanced"] = "Ajustes avanzados",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "Para depuración y comportamiento heredado.",
		["tool.mediaplayer_spatial.section.shared"] = "Ajustes compartidos y del servidor",
		["tool.mediaplayer_spatial.section.shared_desc"] = "Estos ajustes pueden requerir privilegios de administrador en servidores multijugador.",
		["tool.mediaplayer_spatial.cvar.debug"] = "Registro de depuración",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "Permitir solicitudes de páginas web",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "Límite de cola",
		["tool.mediaplayer_spatial.cvar.resolution"] = "Resolución del navegador",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "Activar audio 3D",
		["tool.mediaplayer_spatial.cvar.volume"] = "Volumen",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "Silenciar cuando Garry's Mod no está enfocado",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "Mostrar miniaturas",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "Distancia mínima de proximidad",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "Distancia máxima de proximidad",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "Radio audible espacial",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "Número máximo de repeticiones extra",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "Pantalla completa (obsoleta; sin uso)",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "Filtro de consola JS",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = todos los mensajes de la consola HTML, 1 = ninguno.",
		["mediaplayer.spatial.loop_forever"] = "Repetir para siempre",
		["mediaplayer.spatial.extra_loops"] = "Repeticiones extra",
		["mediaplayer.spatial.footer_hint"] = "El enlace usa la página de solicitud normal de MediaPlayer. Los bucles finitos se cuentan después de la primera reproducción.",
		["mediaplayer.spatial.error_anchor_missing"] = "La ancla de medios espacial seleccionada ya no existe.",
		["mediaplayer.spatial.error_empty_url"] = "Primero introduce una URL de medios.",
		["mediaplayer.spatial.error_invalid_url"] = "La URL solicitada no era válida.",
		["mediaplayer.spatial.error_request_failed"] = "La solicitud falló: %s",
		["mediaplayer.spatial.error_anchor_network"] = "No se pudo abrir la ventana de solicitud de medios espaciales porque el ancla no terminó de sincronizarse a tiempo.",
	},
	["fr"] = {
		["tool.mediaplayer_spatial.name"] = "Lecteur multimédia spatial",
		["tool.mediaplayer_spatial.desc"] = "Fixe l'audio de MediaPlayer dans le monde ou le fait suivre une entité.",
		["tool.mediaplayer_spatial.0"] = "Clic gauche : créer ou rouvrir une source spatiale. Clic droit : la supprimer. Recharger : rouvrir l'interface de requête.",
		["tool.mediaplayer_spatial.help_target"] = "Faites un clic gauche sur un prop, un joueur ou un PNJ pour que l'audio le suive, ou un clic gauche sur le monde pour fixer le son en place.",
		["tool.mediaplayer_spatial.help_popup"] = "La fenêtre utilise la page de requête normale de MediaPlayer. Activez la boucle infinie ou choisissez le nombre de boucles supplémentaires à mettre en file.",
		["tool.mediaplayer_spatial.help_remove"] = "Le clic droit supprime la source spatiale correspondante. Recharger rouvre la fenêtre de requête pour une source existante.",
		["tool.mediaplayer_spatial.section.client"] = "Paramètres client",
		["tool.mediaplayer_spatial.section.client_desc"] = "Ces paramètres n'affectent que votre client local.",
		["tool.mediaplayer_spatial.section.advanced"] = "Paramètres avancés",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "Pour le débogage et le comportement hérité.",
		["tool.mediaplayer_spatial.section.shared"] = "Paramètres partagés et serveur",
		["tool.mediaplayer_spatial.section.shared_desc"] = "Ces paramètres peuvent nécessiter des privilèges d'administrateur sur les serveurs multijoueur.",
		["tool.mediaplayer_spatial.cvar.debug"] = "Journalisation de débogage",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "Autoriser les requêtes de pages web",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "Taille de la file d'attente",
		["tool.mediaplayer_spatial.cvar.resolution"] = "Résolution du navigateur",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "Activer l'audio 3D",
		["tool.mediaplayer_spatial.cvar.volume"] = "Volume",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "Couper le son lorsque Garry's Mod n'est pas au premier plan",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "Afficher les miniatures",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "Proximité minimale",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "Proximité maximale",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "Rayon d'audition spatial",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "Nombre maximal de boucles supplémentaires",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "Plein écran (obsolète ; inutilisé)",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "Filtre de console JS",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = tous les messages de la console HTML, 1 = aucun.",
		["mediaplayer.spatial.loop_forever"] = "Boucle infinie",
		["mediaplayer.spatial.extra_loops"] = "Boucles supplémentaires",
		["mediaplayer.spatial.footer_hint"] = "Le lien utilise la page de requête normale de MediaPlayer. Les boucles finies sont comptées après la première lecture.",
		["mediaplayer.spatial.error_anchor_missing"] = "L'ancre multimédia spatiale sélectionnée n'existe plus.",
		["mediaplayer.spatial.error_empty_url"] = "Veuillez d'abord saisir une URL de média.",
		["mediaplayer.spatial.error_invalid_url"] = "L'URL demandée n'était pas valide.",
		["mediaplayer.spatial.error_request_failed"] = "Échec de la requête : %s",
		["mediaplayer.spatial.error_anchor_network"] = "Impossible d'ouvrir la fenêtre de requête du média spatial, car l'ancre n'a pas fini d'être synchronisée à temps.",
	},
	["ja"] = {
		["tool.mediaplayer_spatial.name"] = "空間メディアプレーヤー",
		["tool.mediaplayer_spatial.desc"] = "MediaPlayer の音声をワールドに固定するか、エンティティに追従させます。",
		["tool.mediaplayer_spatial.0"] = "左クリック：空間音源を作成または再度開きます。右クリック：削除します。リロード：リクエスト UI を再度開きます。",
		["tool.mediaplayer_spatial.help_target"] = "プロップ、プレイヤー、NPC を左クリックすると音声がそれに追従し、ワールドを左クリックするとその場に固定されます。",
		["tool.mediaplayer_spatial.help_popup"] = "ポップアップでは通常の MediaPlayer リクエストブラウザを使用します。無限ループを有効にするか、追加ループ回数を指定してください。",
		["tool.mediaplayer_spatial.help_remove"] = "右クリックで対応する空間音源を削除します。リロードで既存の音源のリクエスト画面を再度開きます。",
		["tool.mediaplayer_spatial.section.client"] = "クライアント設定",
		["tool.mediaplayer_spatial.section.client_desc"] = "これらの設定は自分のクライアントにのみ影響します。",
		["tool.mediaplayer_spatial.section.advanced"] = "詳細設定",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "デバッグと旧挙動向けです。",
		["tool.mediaplayer_spatial.section.shared"] = "共有・サーバー設定",
		["tool.mediaplayer_spatial.section.shared_desc"] = "マルチプレイヤーサーバーでは管理者権限が必要な場合があります。",
		["tool.mediaplayer_spatial.cvar.debug"] = "デバッグログ",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "Web ページのリクエストを許可",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "キュー上限",
		["tool.mediaplayer_spatial.cvar.resolution"] = "ブラウザー解像度",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "3D オーディオを有効化",
		["tool.mediaplayer_spatial.cvar.volume"] = "音量",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "Garry's Mod が非アクティブのときにミュート",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "サムネイルを描画",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "近接最小距離",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "近接最大距離",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "空間可聴半径",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "追加ループ最大回数",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "フルスクリーン（非推奨・未使用）",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "JS コンソールフィルター",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = HTML コンソールメッセージをすべて表示、1 = 何も表示しません。",
		["mediaplayer.spatial.loop_forever"] = "無限ループ",
		["mediaplayer.spatial.extra_loops"] = "追加ループ",
		["mediaplayer.spatial.footer_hint"] = "リンクは通常の MediaPlayer リクエストページを使用します。有限ループは最初の再生後に数えられます。",
		["mediaplayer.spatial.error_anchor_missing"] = "選択した空間メディアアンカーはもう存在しません。",
		["mediaplayer.spatial.error_empty_url"] = "先にメディア URL を入力してください。",
		["mediaplayer.spatial.error_invalid_url"] = "要求された URL は無効でした。",
		["mediaplayer.spatial.error_request_failed"] = "リクエストに失敗しました: %s",
		["mediaplayer.spatial.error_anchor_network"] = "アンカーのネットワーク同期が間に合わなかったため、空間メディアのリクエストウィンドウを開けませんでした。",
	},
	["ko"] = {
		["tool.mediaplayer_spatial.name"] = "공간 미디어 플레이어",
		["tool.mediaplayer_spatial.desc"] = "MediaPlayer 오디오를 월드에 고정하거나 엔티티를 따라가게 합니다.",
		["tool.mediaplayer_spatial.0"] = "왼쪽 클릭: 공간 음원을 만들거나 다시 엽니다. 오른쪽 클릭: 제거합니다. 재장전: 요청 UI를 다시 엽니다.",
		["tool.mediaplayer_spatial.help_target"] = "프롭, 플레이어 또는 NPC를 왼쪽 클릭하면 오디오가 대상을 따라가고, 월드를 왼쪽 클릭하면 그 위치에 고정됩니다.",
		["tool.mediaplayer_spatial.help_popup"] = "팝업은 일반 MediaPlayer 요청 브라우저를 사용합니다. 무한 반복을 켜거나 추가 반복 횟수를 지정하세요.",
		["tool.mediaplayer_spatial.help_remove"] = "오른쪽 클릭은 해당 공간 음원을 제거합니다. 재장전은 기존 음원의 요청 창을 다시 엽니다.",
		["tool.mediaplayer_spatial.section.client"] = "클라이언트 설정",
		["tool.mediaplayer_spatial.section.client_desc"] = "이 설정은 내 로컬 클라이언트에만 적용됩니다.",
		["tool.mediaplayer_spatial.section.advanced"] = "고급 설정",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "디버깅 및 이전 동작용입니다.",
		["tool.mediaplayer_spatial.section.shared"] = "공유 및 서버 설정",
		["tool.mediaplayer_spatial.section.shared_desc"] = "멀티플레이어 서버에서는 관리자 권한이 필요할 수 있습니다.",
		["tool.mediaplayer_spatial.cvar.debug"] = "디버그 로그",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "웹페이지 요청 허용",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "대기열 한도",
		["tool.mediaplayer_spatial.cvar.resolution"] = "브라우저 해상도",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "3D 오디오 사용",
		["tool.mediaplayer_spatial.cvar.volume"] = "볼륨",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "Garry's Mod가 포커스를 잃으면 음소거",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "썸네일 표시",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "근접 최소 거리",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "근접 최대 거리",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "공간 청취 반경",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "추가 반복 최대 횟수",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "전체 화면(사용 중단됨/미사용)",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "JS 콘솔 필터",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = HTML 콘솔 메시지 모두 표시, 1 = 표시 안 함.",
		["mediaplayer.spatial.loop_forever"] = "무한 반복",
		["mediaplayer.spatial.extra_loops"] = "추가 반복",
		["mediaplayer.spatial.footer_hint"] = "링크는 일반 MediaPlayer 요청 페이지를 사용합니다. 유한 반복은 첫 재생 후에 계산됩니다.",
		["mediaplayer.spatial.error_anchor_missing"] = "선택한 공간 미디어 앵커가 더 이상 존재하지 않습니다.",
		["mediaplayer.spatial.error_empty_url"] = "먼저 미디어 URL을 입력하세요.",
		["mediaplayer.spatial.error_invalid_url"] = "요청한 URL이 올바르지 않습니다.",
		["mediaplayer.spatial.error_request_failed"] = "요청 실패: %s",
		["mediaplayer.spatial.error_anchor_network"] = "앵커 네트워킹이 제때 끝나지 않아 공간 미디어 요청 창을 열 수 없었습니다.",
	},
	["ru"] = {
		["tool.mediaplayer_spatial.name"] = "Пространственный медиаплеер",
		["tool.mediaplayer_spatial.desc"] = "Закрепляет звук MediaPlayer в мире или заставляет его следовать за сущностью.",
		["tool.mediaplayer_spatial.0"] = "ЛКМ: создать или снова открыть пространственный источник. ПКМ: удалить его. Перезарядка: снова открыть интерфейс запроса.",
		["tool.mediaplayer_spatial.help_target"] = "Нажмите ЛКМ по пропу, игроку или NPC, чтобы звук следовал за ним, либо ЛКМ по миру, чтобы закрепить звук на месте.",
		["tool.mediaplayer_spatial.help_popup"] = "Во всплывающем окне используется обычный браузер запросов MediaPlayer. Включите бесконечный цикл или выберите, сколько дополнительных повторов поставить в очередь.",
		["tool.mediaplayer_spatial.help_remove"] = "ПКМ удаляет соответствующий пространственный источник. Перезарядка снова открывает окно запроса для существующего источника.",
		["tool.mediaplayer_spatial.section.client"] = "Клиентские настройки",
		["tool.mediaplayer_spatial.section.client_desc"] = "Эти настройки влияют только на ваш локальный клиент.",
		["tool.mediaplayer_spatial.section.advanced"] = "Дополнительные настройки",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "Для отладки и устаревшего поведения.",
		["tool.mediaplayer_spatial.section.shared"] = "Общие и серверные настройки",
		["tool.mediaplayer_spatial.section.shared_desc"] = "На многопользовательских серверах для этих настроек могут потребоваться права администратора.",
		["tool.mediaplayer_spatial.cvar.debug"] = "Журнал отладки",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "Разрешить запросы веб-страниц",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "Лимит очереди",
		["tool.mediaplayer_spatial.cvar.resolution"] = "Разрешение браузера",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "Включить 3D-аудио",
		["tool.mediaplayer_spatial.cvar.volume"] = "Громкость",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "Заглушать, когда Garry's Mod не в фокусе",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "Отрисовывать миниатюры",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "Минимум близости",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "Максимум близости",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "Радиус слышимости пространственного звука",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "Максимум дополнительных повторов",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "Полноэкранный режим (устарел; не используется)",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "Фильтр консоли JS",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = все сообщения консоли HTML, 1 = ни одного.",
		["mediaplayer.spatial.loop_forever"] = "Бесконечный цикл",
		["mediaplayer.spatial.extra_loops"] = "Дополнительные повторы",
		["mediaplayer.spatial.footer_hint"] = "Ссылка использует обычную страницу запроса MediaPlayer. Ограниченные повторы считаются после первого воспроизведения.",
		["mediaplayer.spatial.error_anchor_missing"] = "Выбранный пространственный медиа-якорь больше не существует.",
		["mediaplayer.spatial.error_empty_url"] = "Сначала введите URL медиа.",
		["mediaplayer.spatial.error_invalid_url"] = "Запрошенный URL недействителен.",
		["mediaplayer.spatial.error_request_failed"] = "Ошибка запроса: %s",
		["mediaplayer.spatial.error_anchor_network"] = "Не удалось открыть окно запроса пространственного медиа, потому что якорь не успел завершить сетевую синхронизацию.",
	},
	["zh-CN"] = {
		["tool.mediaplayer_spatial.name"] = "空间媒体播放器",
		["tool.mediaplayer_spatial.desc"] = "将 MediaPlayer 音频固定在世界中，或让它跟随实体。",
		["tool.mediaplayer_spatial.0"] = "左键：创建或重新打开空间音源。右键：移除它。装弹键：重新打开请求界面。",
		["tool.mediaplayer_spatial.help_target"] = "左键点击道具、玩家或 NPC 可让音频跟随目标；左键点击世界可将声音固定在该位置。",
		["tool.mediaplayer_spatial.help_popup"] = "弹出窗口使用普通的 MediaPlayer 请求浏览器。可设置无限循环，或选择额外循环次数。",
		["tool.mediaplayer_spatial.help_remove"] = "右键会移除对应的空间音源。装弹键会为现有音源重新打开请求窗口。",
		["tool.mediaplayer_spatial.section.client"] = "客户端设置",
		["tool.mediaplayer_spatial.section.client_desc"] = "这些设置只影响你的本地客户端。",
		["tool.mediaplayer_spatial.section.advanced"] = "高级设置",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "用于调试和旧行为。",
		["tool.mediaplayer_spatial.section.shared"] = "共享和服务器设置",
		["tool.mediaplayer_spatial.section.shared_desc"] = "在多人服务器中，这些设置可能需要管理员权限。",
		["tool.mediaplayer_spatial.cvar.debug"] = "调试日志",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "允许网页请求",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "队列上限",
		["tool.mediaplayer_spatial.cvar.resolution"] = "浏览器分辨率",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "启用 3D 音频",
		["tool.mediaplayer_spatial.cvar.volume"] = "音量",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "当 Garry's Mod 失去焦点时静音",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "绘制缩略图",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "近距离最小值",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "近距离最大值",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "空间可听半径",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "额外循环最大次数",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "全屏（已弃用；未使用）",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "JS 控制台过滤",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = 显示所有 HTML 控制台消息，1 = 全部隐藏。",
		["mediaplayer.spatial.loop_forever"] = "无限循环",
		["mediaplayer.spatial.extra_loops"] = "额外循环",
		["mediaplayer.spatial.footer_hint"] = "链接使用普通的 MediaPlayer 请求页面。有限循环会在首次播放后开始计数。",
		["mediaplayer.spatial.error_anchor_missing"] = "所选的空间媒体锚点已不存在。",
		["mediaplayer.spatial.error_empty_url"] = "请先输入媒体 URL。",
		["mediaplayer.spatial.error_invalid_url"] = "请求的 URL 无效。",
		["mediaplayer.spatial.error_request_failed"] = "请求失败：%s",
		["mediaplayer.spatial.error_anchor_network"] = "无法打开空间媒体请求窗口，因为锚点没有及时完成网络同步。",
	},
	["zh-TW"] = {
		["tool.mediaplayer_spatial.name"] = "空間媒體播放器",
		["tool.mediaplayer_spatial.desc"] = "將 MediaPlayer 音訊固定在世界中，或讓它跟隨實體。",
		["tool.mediaplayer_spatial.0"] = "左鍵：建立或重新開啟空間音源。右鍵：移除它。裝填鍵：重新開啟請求介面。",
		["tool.mediaplayer_spatial.help_target"] = "左鍵點擊道具、玩家或 NPC 可讓音訊跟隨目標；左鍵點擊世界可將聲音固定在該位置。",
		["tool.mediaplayer_spatial.help_popup"] = "彈出視窗使用一般的 MediaPlayer 請求瀏覽器。可設定無限循環，或選擇額外循環次數。",
		["tool.mediaplayer_spatial.help_remove"] = "右鍵會移除對應的空間音源。裝填鍵會為現有音源重新開啟請求視窗。",
		["tool.mediaplayer_spatial.section.client"] = "用戶端設定",
		["tool.mediaplayer_spatial.section.client_desc"] = "這些設定只影響你的本機用戶端。",
		["tool.mediaplayer_spatial.section.advanced"] = "進階設定",
		["tool.mediaplayer_spatial.section.advanced_desc"] = "用於除錯和舊行為。",
		["tool.mediaplayer_spatial.section.shared"] = "共用和伺服器設定",
		["tool.mediaplayer_spatial.section.shared_desc"] = "在多人伺服器中，這些設定可能需要管理員權限。",
		["tool.mediaplayer_spatial.cvar.debug"] = "除錯日誌",
		["tool.mediaplayer_spatial.cvar.allow_webpages"] = "允許網頁請求",
		["tool.mediaplayer_spatial.cvar.queue_limit"] = "佇列上限",
		["tool.mediaplayer_spatial.cvar.resolution"] = "瀏覽器解析度",
		["tool.mediaplayer_spatial.cvar.audio3d"] = "啟用 3D 音訊",
		["tool.mediaplayer_spatial.cvar.volume"] = "音量",
		["tool.mediaplayer_spatial.cvar.mute_unfocused"] = "當 Garry's Mod 失去焦點時靜音",
		["tool.mediaplayer_spatial.cvar.draw_thumbnails"] = "繪製縮圖",
		["tool.mediaplayer_spatial.cvar.proximity_min"] = "近距離最小值",
		["tool.mediaplayer_spatial.cvar.proximity_max"] = "近距離最大值",
		["tool.mediaplayer_spatial.cvar.hear_radius"] = "空間可聽半徑",
		["tool.mediaplayer_spatial.cvar.max_repeat_count"] = "額外循環最大次數",
		["tool.mediaplayer_spatial.cvar.fullscreen"] = "全螢幕（已棄用；未使用）",
		["tool.mediaplayer_spatial.cvar.js_console_filter"] = "JS 主控台過濾",
		["tool.mediaplayer_spatial.cvar.js_console_filter_desc"] = "0 = 顯示所有 HTML 主控台訊息，1 = 全部隱藏。",
		["mediaplayer.spatial.loop_forever"] = "無限循環",
		["mediaplayer.spatial.extra_loops"] = "額外循環",
		["mediaplayer.spatial.footer_hint"] = "連結使用一般的 MediaPlayer 請求頁面。有限循環會在首次播放後開始計數。",
		["mediaplayer.spatial.error_anchor_missing"] = "所選的空間媒體錨點已不存在。",
		["mediaplayer.spatial.error_empty_url"] = "請先輸入媒體 URL。",
		["mediaplayer.spatial.error_invalid_url"] = "請求的 URL 無效。",
		["mediaplayer.spatial.error_request_failed"] = "請求失敗：%s",
		["mediaplayer.spatial.error_anchor_network"] = "無法開啟空間媒體請求視窗，因為錨點沒有及時完成網路同步。",
	},
}

local function ResolveLanguage( lang )
	if Translations[lang] then
		return lang
	end

	if lang == "zh" then
		return "zh-CN"
	end

	return "en"
end

local function ApplyTranslations()
	local lang = "en"
	local cvar = GetConVar( "gmod_language" )
	if cvar then
		lang = ResolveLanguage( cvar:GetString() )
	end

	local phrases = {}
	for key, value in pairs( Translations.en or {} ) do
		phrases[key] = value
	end

	if lang ~= "en" then
		for key, value in pairs( Translations[lang] or {} ) do
			phrases[key] = value
		end
	end

	for key, value in pairs( phrases ) do
		language.Add( key, value )
	end
end

ApplyTranslations()
cvars.AddChangeCallback( "gmod_language", function()
	ApplyTranslations()
end, "MediaPlayerSpatialLocalization" )
